# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(518, 400)
        Form.setMinimumSize(QtCore.QSize(0, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 120))
        self.label.setMaximumSize(QtCore.QSize(500, 120))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./pages/UIs/../../icons/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "About"))
        self.label_2.setText(_translate("Form", "This application is developed by the Michigan Technological University (MTU) team at American Center for Mobility (ACM). It provides an intuitive interface for synchronizing and visualizing video, sensor data, and GPS information in a unified, interactive environment.\n"
"\n"
"Designed with research and field data analysis in mind, it enables streamlined workflows for video playback, signal plotting, and real-time map visualization.\n"
"\n"
"This project was developed by the MTU-APSRC at ACM, aiming to create accessible tools that support innovation in data-driven research and engineering.\n"
"\n"
"© 2025 ACM Powered By MTU\n"
"For more information, please visit: https://www.mtu.edu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
