# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\APSRC\ads_app\pages\UIs\auto_scenario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wiz_1(object):
    def setupUi(self, Wiz_1):
        Wiz_1.setObjectName("Wiz_1")
        Wiz_1.resize(488, 330)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Wiz_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Wiz_1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scen_list = QtWidgets.QListWidget(Wiz_1)
        self.scen_list.setDragEnabled(False)
        self.scen_list.setObjectName("scen_list")
        self.horizontalLayout.addWidget(self.scen_list)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.detectB = QtWidgets.QPushButton(Wiz_1)
        self.detectB.setObjectName("detectB")
        self.verticalLayout.addWidget(self.detectB)
        spacerItem = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.exportB = QtWidgets.QPushButton(Wiz_1)
        self.exportB.setObjectName("exportB")
        self.verticalLayout.addWidget(self.exportB)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Wiz_1)
        QtCore.QMetaObject.connectSlotsByName(Wiz_1)

    def retranslateUi(self, Wiz_1):
        _translate = QtCore.QCoreApplication.translate
        Wiz_1.setWindowTitle(_translate("Wiz_1", "Automated Scenario Detection Tool"))
        self.label.setText(_translate("Wiz_1", "Select scenario(s) to export"))
        self.scen_list.setSortingEnabled(False)
        self.detectB.setText(_translate("Wiz_1", "Auto Detect"))
        self.exportB.setText(_translate("Wiz_1", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wiz_1 = QtWidgets.QWidget()
    ui = Ui_Wiz_1()
    ui.setupUi(Wiz_1)
    Wiz_1.show()
    sys.exit(app.exec_())
