# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/bag_to_csv.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 457)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bagList = QtWidgets.QListWidget(Form)
        self.bagList.setObjectName("bagList")
        self.horizontalLayout_3.addWidget(self.bagList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.openBagB = QtWidgets.QPushButton(Form)
        self.openBagB.setObjectName("openBagB")
        self.verticalLayout.addWidget(self.openBagB)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.config = QtWidgets.QListWidget(Form)
        self.config.setMinimumSize(QtCore.QSize(0, 25))
        self.config.setMaximumSize(QtCore.QSize(16777215, 25))
        self.config.setObjectName("config")
        self.horizontalLayout_2.addWidget(self.config)
        self.openConfB = QtWidgets.QPushButton(Form)
        self.openConfB.setObjectName("openConfB")
        self.horizontalLayout_2.addWidget(self.openConfB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.processors = QtWidgets.QSpinBox(Form)
        self.processors.setMinimum(1)
        self.processors.setMaximum(20)
        self.processors.setObjectName("processors")
        self.horizontalLayout.addWidget(self.processors)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.override = QtWidgets.QCheckBox(Form)
        self.override.setObjectName("override")
        self.horizontalLayout.addWidget(self.override)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.reportList = QtWidgets.QListWidget(Form)
        self.reportList.setObjectName("reportList")
        self.verticalLayout_2.addWidget(self.reportList)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.closeB = QtWidgets.QPushButton(Form)
        self.closeB.setObjectName("closeB")
        self.horizontalLayout_4.addWidget(self.closeB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bag to CSV"))
        self.label_2.setText(_translate("Form", "Select ROSBAG(s):"))
        self.openBagB.setText(_translate("Form", "Browse"))
        self.label_3.setText(_translate("Form", "Select Config File:"))
        self.openConfB.setText(_translate("Form", "Browse"))
        self.label.setText(_translate("Form", "Number of parallel processors:"))
        self.override.setText(_translate("Form", "Override"))
        self.label_4.setText(_translate("Form", "Report"))
        self.closeB.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
