# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/here_api.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(877, 584)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.refreshButton = QtWidgets.QPushButton(self.groupBox)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_3.addWidget(self.refreshButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.mapView = QtWidgets.QLabel(self.groupBox)
        self.mapView.setObjectName("mapView")
        self.verticalLayout.addWidget(self.mapView)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status_txt = QtWidgets.QLabel(Form)
        self.status_txt.setObjectName("status_txt")
        self.horizontalLayout_2.addWidget(self.status_txt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.seg_num = QtWidgets.QSpinBox(Form)
        self.seg_num.setMinimum(1)
        self.seg_num.setProperty("value", 20)
        self.seg_num.setObjectName("seg_num")
        self.horizontalLayout.addWidget(self.seg_num)
        spacerItem2 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.runBut = QtWidgets.QPushButton(Form)
        self.runBut.setObjectName("runBut")
        self.horizontalLayout.addWidget(self.runBut)
        self.exportBut = QtWidgets.QPushButton(Form)
        self.exportBut.setObjectName("exportBut")
        self.horizontalLayout.addWidget(self.exportBut)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "HERE API Tool"))
        self.groupBox.setTitle(_translate("Form", "Map View"))
        self.refreshButton.setText(_translate("Form", "Refresh Map"))
        self.mapView.setText(_translate("Form", "MAP"))
        self.status_txt.setText(_translate("Form", "status"))
        self.label_2.setText(_translate("Form", "Number of segments"))
        self.runBut.setText(_translate("Form", "Run"))
        self.exportBut.setText(_translate("Form", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
