# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/lidar_process.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(416, 307)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dads_pwd = QtWidgets.QListWidget(Form)
        self.dads_pwd.setMinimumSize(QtCore.QSize(0, 30))
        self.dads_pwd.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dads_pwd.setObjectName("dads_pwd")
        self.horizontalLayout.addWidget(self.dads_pwd)
        self.browseB = QtWidgets.QPushButton(Form)
        self.browseB.setObjectName("browseB")
        self.horizontalLayout.addWidget(self.browseB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.csvList = QtWidgets.QListWidget(Form)
        self.csvList.setObjectName("csvList")
        self.verticalLayout.addWidget(self.csvList)
        self.report = QtWidgets.QLabel(Form)
        self.report.setText("")
        self.report.setObjectName("report")
        self.verticalLayout.addWidget(self.report)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.applyB = QtWidgets.QPushButton(Form)
        self.applyB.setObjectName("applyB")
        self.horizontalLayout_2.addWidget(self.applyB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lidar Data Clean Up"))
        self.label.setText(_translate("Form", "Select *.DADS"))
        self.browseB.setText(_translate("Form", "Browse"))
        self.label_2.setText(_translate("Form", "Select csv(s)"))
        self.applyB.setText(_translate("Form", "Clean Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
