# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/addPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plot(object):
    def setupUi(self, plot):
        plot.setObjectName("plot")
        plot.resize(396, 243)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(plot)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(plot)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.colList = QtWidgets.QListWidget(plot)
        self.colList.setDragEnabled(False)
        self.colList.setObjectName("colList")
        self.horizontalLayout.addWidget(self.colList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.doneB = QtWidgets.QPushButton(plot)
        self.doneB.setObjectName("doneB")
        self.verticalLayout.addWidget(self.doneB)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(plot)
        QtCore.QMetaObject.connectSlotsByName(plot)

    def retranslateUi(self, plot):
        _translate = QtCore.QCoreApplication.translate
        plot.setWindowTitle(_translate("plot", "Add Plot"))
        self.label.setText(_translate("plot", "Select Columns(s)"))
        self.colList.setSortingEnabled(False)
        self.doneB.setText(_translate("plot", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    plot = QtWidgets.QWidget()
    ui = Ui_plot()
    ui.setupUi(plot)
    plot.show()
    sys.exit(app.exec_())
