# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/scenario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addScenario(object):
    def setupUi(self, addScenario):
        addScenario.setObjectName("addScenario")
        addScenario.resize(514, 220)
        self.verticalLayout = QtWidgets.QVBoxLayout(addScenario)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(addScenario)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.time = QtWidgets.QPlainTextEdit(addScenario)
        self.time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.time.setObjectName("time")
        self.horizontalLayout.addWidget(self.time)
        spacerItem = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(addScenario)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.scenario = QtWidgets.QComboBox(addScenario)
        self.scenario.setObjectName("scenario")
        self.horizontalLayout_2.addWidget(self.scenario)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(addScenario)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(538, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.customScen = QtWidgets.QPlainTextEdit(addScenario)
        self.customScen.setObjectName("customScen")
        self.verticalLayout.addWidget(self.customScen)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(498, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.addB = QtWidgets.QPushButton(addScenario)
        self.addB.setObjectName("addB")
        self.horizontalLayout_4.addWidget(self.addB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(addScenario)
        QtCore.QMetaObject.connectSlotsByName(addScenario)

    def retranslateUi(self, addScenario):
        _translate = QtCore.QCoreApplication.translate
        addScenario.setWindowTitle(_translate("addScenario", "Add/Edit Scenario"))
        self.label.setText(_translate("addScenario", "ROS Time"))
        self.label_2.setText(_translate("addScenario", "Scenario"))
        self.label_3.setText(_translate("addScenario", "Custom Scenario"))
        self.addB.setText(_translate("addScenario", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addScenario = QtWidgets.QWidget()
    ui = Ui_addScenario()
    ui.setupUi(addScenario)
    addScenario.show()
    sys.exit(app.exec_())
