# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pages/UIs/scenario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addScenario(object):
    def setupUi(self, addScenario):
        addScenario.setObjectName("addScenario")
        addScenario.resize(712, 204)
        self.label = QtWidgets.QLabel(addScenario)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.label.setObjectName("label")
        self.scenario = QtWidgets.QComboBox(addScenario)
        self.scenario.setGeometry(QtCore.QRect(100, 40, 591, 22))
        self.scenario.setObjectName("scenario")
        self.label_2 = QtWidgets.QLabel(addScenario)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.addB = QtWidgets.QPushButton(addScenario)
        self.addB.setGeometry(QtCore.QRect(620, 170, 75, 23))
        self.addB.setObjectName("addB")
        self.discardB = QtWidgets.QPushButton(addScenario)
        self.discardB.setGeometry(QtCore.QRect(540, 170, 75, 23))
        self.discardB.setObjectName("discardB")
        self.time = QtWidgets.QPlainTextEdit(addScenario)
        self.time.setGeometry(QtCore.QRect(100, 10, 311, 21))
        self.time.setObjectName("time")
        self.label_3 = QtWidgets.QLabel(addScenario)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 121, 16))
        self.label_3.setObjectName("label_3")
        self.customScen = QtWidgets.QPlainTextEdit(addScenario)
        self.customScen.setGeometry(QtCore.QRect(20, 90, 671, 70))
        self.customScen.setObjectName("customScen")

        self.retranslateUi(addScenario)
        QtCore.QMetaObject.connectSlotsByName(addScenario)

    def retranslateUi(self, addScenario):
        _translate = QtCore.QCoreApplication.translate
        addScenario.setWindowTitle(_translate("addScenario", "Add/Edit Scenario"))
        self.label.setText(_translate("addScenario", "ROS Time"))
        self.label_2.setText(_translate("addScenario", "Scenario"))
        self.addB.setText(_translate("addScenario", "Done"))
        self.discardB.setText(_translate("addScenario", "Discard"))
        self.label_3.setText(_translate("addScenario", "Custom Scenario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addScenario = QtWidgets.QWidget()
    ui = Ui_addScenario()
    ui.setupUi(addScenario)
    addScenario.show()
    sys.exit(app.exec_())
