# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pages\UIs\scenario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addScenario(object):
    def setupUi(self, addScenario):
        addScenario.setObjectName("addScenario")
        addScenario.resize(712, 101)
        self.time = QtWidgets.QSpinBox(addScenario)
        self.time.setGeometry(QtCore.QRect(76, 31, 201, 20))
        self.time.setObjectName("time")
        self.label = QtWidgets.QLabel(addScenario)
        self.label.setGeometry(QtCore.QRect(21, 31, 46, 16))
        self.label.setObjectName("label")
        self.scenario = QtWidgets.QComboBox(addScenario)
        self.scenario.setGeometry(QtCore.QRect(360, 30, 331, 22))
        self.scenario.setObjectName("scenario")
        self.label_2 = QtWidgets.QLabel(addScenario)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 46, 16))
        self.label_2.setObjectName("label_2")
        self.addB = QtWidgets.QPushButton(addScenario)
        self.addB.setGeometry(QtCore.QRect(620, 70, 75, 23))
        self.addB.setObjectName("addB")
        self.discardB = QtWidgets.QPushButton(addScenario)
        self.discardB.setGeometry(QtCore.QRect(540, 70, 75, 23))
        self.discardB.setObjectName("discardB")

        self.retranslateUi(addScenario)
        QtCore.QMetaObject.connectSlotsByName(addScenario)

    def retranslateUi(self, addScenario):
        _translate = QtCore.QCoreApplication.translate
        addScenario.setWindowTitle(_translate("addScenario", "Add/Edit Scenario"))
        self.label.setText(_translate("addScenario", "ROS Time"))
        self.label_2.setText(_translate("addScenario", "Scenario"))
        self.addB.setText(_translate("addScenario", "Add"))
        self.discardB.setText(_translate("addScenario", "Discard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addScenario = QtWidgets.QWidget()
    ui = Ui_addScenario()
    ui.setupUi(addScenario)
    addScenario.show()
    sys.exit(app.exec_())
