# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/video.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 311)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 661, 71))
        self.groupBox.setObjectName("groupBox")
        self.browseB = QtWidgets.QPushButton(self.groupBox)
        self.browseB.setGeometry(QtCore.QRect(560, 30, 89, 31))
        self.browseB.setObjectName("browseB")
        self.pwd = QtWidgets.QTextBrowser(self.groupBox)
        self.pwd.setGeometry(QtCore.QRect(20, 30, 531, 31))
        self.pwd.setObjectName("pwd")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 431, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.displayL = QtWidgets.QLabel(self.groupBox_2)
        self.displayL.setGeometry(QtCore.QRect(10, 30, 411, 151))
        self.displayL.setScaledContents(True)
        self.displayL.setObjectName("displayL")
        self.timeCtrl = QtWidgets.QSlider(self.groupBox_2)
        self.timeCtrl.setGeometry(QtCore.QRect(50, 190, 371, 31))
        self.timeCtrl.setOrientation(QtCore.Qt.Horizontal)
        self.timeCtrl.setObjectName("timeCtrl")
        self.playB = QtWidgets.QPushButton(self.groupBox_2)
        self.playB.setGeometry(QtCore.QRect(10, 190, 31, 25))
        self.playB.setObjectName("playB")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 80, 221, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.leftC = QtWidgets.QCheckBox(self.groupBox_3)
        self.leftC.setGeometry(QtCore.QRect(11, 31, 53, 23))
        self.leftC.setObjectName("leftC")
        self.rightC = QtWidgets.QCheckBox(self.groupBox_3)
        self.rightC.setGeometry(QtCore.QRect(11, 60, 62, 23))
        self.rightC.setObjectName("rightC")
        self.rotateC = QtWidgets.QCheckBox(self.groupBox_3)
        self.rotateC.setGeometry(QtCore.QRect(11, 89, 72, 23))
        self.rotateC.setObjectName("rotateC")
        self.applyB = QtWidgets.QPushButton(self.groupBox_3)
        self.applyB.setGeometry(QtCore.QRect(120, 80, 89, 25))
        self.applyB.setObjectName("applyB")
        self.doneB = QtWidgets.QPushButton(Form)
        self.doneB.setGeometry(QtCore.QRect(450, 270, 221, 31))
        self.doneB.setObjectName("doneB")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 200, 221, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.progress = QtWidgets.QProgressBar(self.groupBox_4)
        self.progress.setGeometry(QtCore.QRect(10, 30, 201, 23))
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Video Process Tool"))
        self.groupBox.setTitle(_translate("Form", "Original Video File"))
        self.browseB.setText(_translate("Form", "Browse"))
        self.groupBox_2.setTitle(_translate("Form", "Display"))
        self.displayL.setText(_translate("Form", "TextLabel"))
        self.playB.setText(_translate("Form", "P"))
        self.groupBox_3.setTitle(_translate("Form", "Modifications"))
        self.leftC.setText(_translate("Form", "Left"))
        self.rightC.setText(_translate("Form", "Right"))
        self.rotateC.setText(_translate("Form", "Rotate"))
        self.applyB.setText(_translate("Form", "Apply"))
        self.doneB.setText(_translate("Form", "Done"))
        self.groupBox_4.setTitle(_translate("Form", "Progress"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
