# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/wizard4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView



class Ui_Wiz_4(object):
    def setupUi(self, Wiz_4):
        Wiz_4.setObjectName("Wiz_4")
        Wiz_4.resize(493, 330)
        self.label = QtWidgets.QLabel(Wiz_4)
        self.label.setGeometry(QtCore.QRect(190, 10, 61, 21))
        self.label.setObjectName("label")
        self.finishB = QtWidgets.QPushButton(Wiz_4)
        self.finishB.setGeometry(QtCore.QRect(390, 290, 89, 24))
        self.finishB.setObjectName("finishB")
        self.previousB = QtWidgets.QPushButton(Wiz_4)
        self.previousB.setGeometry(QtCore.QRect(390, 260, 89, 25))
        self.previousB.setObjectName("previousB")
        self.webView = QWebEngineView(Wiz_4)
        self.webView.setGeometry(QtCore.QRect(10, 100, 371, 211))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.gpsList = QtWidgets.QListWidget(Wiz_4)
        self.gpsList.setGeometry(QtCore.QRect(10, 40, 371, 51))
        self.gpsList.setObjectName("gpsList")
        self.generateB = QtWidgets.QPushButton(Wiz_4)
        self.generateB.setGeometry(QtCore.QRect(390, 40, 89, 51))
        self.generateB.setObjectName("generateB")

        self.retranslateUi(Wiz_4)
        QtCore.QMetaObject.connectSlotsByName(Wiz_4)

    def retranslateUi(self, Wiz_4):
        _translate = QtCore.QCoreApplication.translate
        Wiz_4.setWindowTitle(_translate("Wiz_4", "Create *.DADS File Wizard (2/x)"))
        self.label.setText(_translate("Wiz_4", "Add Map"))
        self.finishB.setText(_translate("Wiz_4", "Finish"))
        self.previousB.setText(_translate("Wiz_4", "Previous"))
        self.generateB.setText(_translate("Wiz_4", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wiz_4 = QtWidgets.QWidget()
    ui = Ui_Wiz_4()
    ui.setupUi(Wiz_4)
    Wiz_4.show()
    sys.exit(app.exec_())
