# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/wizard4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wiz_4(object):
    def setupUi(self, Wiz_4):
        Wiz_4.setObjectName("Wiz_4")
        Wiz_4.resize(513, 329)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Wiz_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Wiz_4)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gpsList = QtWidgets.QListWidget(Wiz_4)
        self.gpsList.setMinimumSize(QtCore.QSize(0, 60))
        self.gpsList.setMaximumSize(QtCore.QSize(16777215, 60))
        self.gpsList.setObjectName("gpsList")
        self.verticalLayout_2.addWidget(self.gpsList)
        self.webView = QtWidgets.QLabel(Wiz_4)
        self.webView.setObjectName("webView")
        self.verticalLayout_2.addWidget(self.webView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.generateB = QtWidgets.QPushButton(Wiz_4)
        self.generateB.setObjectName("generateB")
        self.verticalLayout.addWidget(self.generateB)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.previousB = QtWidgets.QPushButton(Wiz_4)
        self.previousB.setObjectName("previousB")
        self.verticalLayout.addWidget(self.previousB)
        self.finishB = QtWidgets.QPushButton(Wiz_4)
        self.finishB.setObjectName("finishB")
        self.verticalLayout.addWidget(self.finishB)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Wiz_4)
        QtCore.QMetaObject.connectSlotsByName(Wiz_4)

    def retranslateUi(self, Wiz_4):
        _translate = QtCore.QCoreApplication.translate
        Wiz_4.setWindowTitle(_translate("Wiz_4", "Create *.DADS File Wizard (2/x)"))
        self.label.setText(_translate("Wiz_4", "Add Map"))
        self.webView.setText(_translate("Wiz_4", "TextLabel"))
        self.generateB.setText(_translate("Wiz_4", "Generate"))
        self.previousB.setText(_translate("Wiz_4", "Previous"))
        self.finishB.setText(_translate("Wiz_4", "Finish"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wiz_4 = QtWidgets.QWidget()
    ui = Ui_Wiz_4()
    ui.setupUi(Wiz_4)
    Wiz_4.show()
    sys.exit(app.exec_())
