# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/wizard1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wiz_1(object):
    def setupUi(self, Wiz_1):
        Wiz_1.setObjectName("Wiz_1")
        Wiz_1.resize(488, 330)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Wiz_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Wiz_1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.baglist = QtWidgets.QListWidget(Wiz_1)
        self.baglist.setDragEnabled(False)
        self.baglist.setObjectName("baglist")
        self.horizontalLayout.addWidget(self.baglist)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addB = QtWidgets.QPushButton(Wiz_1)
        self.addB.setObjectName("addB")
        self.verticalLayout.addWidget(self.addB)
        self.removeB = QtWidgets.QPushButton(Wiz_1)
        self.removeB.setObjectName("removeB")
        self.verticalLayout.addWidget(self.removeB)
        self.moveUpB = QtWidgets.QPushButton(Wiz_1)
        self.moveUpB.setObjectName("moveUpB")
        self.verticalLayout.addWidget(self.moveUpB)
        self.moveDownB = QtWidgets.QPushButton(Wiz_1)
        self.moveDownB.setObjectName("moveDownB")
        self.verticalLayout.addWidget(self.moveDownB)
        self.sortB = QtWidgets.QPushButton(Wiz_1)
        self.sortB.setObjectName("sortB")
        self.verticalLayout.addWidget(self.sortB)
        self.toCsvB = QtWidgets.QPushButton(Wiz_1)
        self.toCsvB.setObjectName("toCsvB")
        self.verticalLayout.addWidget(self.toCsvB)
        spacerItem = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.nextB = QtWidgets.QPushButton(Wiz_1)
        self.nextB.setObjectName("nextB")
        self.verticalLayout.addWidget(self.nextB)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Wiz_1)
        QtCore.QMetaObject.connectSlotsByName(Wiz_1)

    def retranslateUi(self, Wiz_1):
        _translate = QtCore.QCoreApplication.translate
        Wiz_1.setWindowTitle(_translate("Wiz_1", "Create *.DADS File Wizard "))
        self.label.setText(_translate("Wiz_1", "Select rosbag file(s)"))
        self.baglist.setSortingEnabled(False)
        self.addB.setText(_translate("Wiz_1", "Add"))
        self.removeB.setText(_translate("Wiz_1", "Remove"))
        self.moveUpB.setText(_translate("Wiz_1", "Move Up"))
        self.moveDownB.setText(_translate("Wiz_1", "Move Down"))
        self.sortB.setText(_translate("Wiz_1", "Sort A->Z"))
        self.toCsvB.setText(_translate("Wiz_1", "To CSV Tool"))
        self.nextB.setText(_translate("Wiz_1", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wiz_1 = QtWidgets.QWidget()
    ui = Ui_Wiz_1()
    ui.setupUi(Wiz_1)
    Wiz_1.show()
    sys.exit(app.exec_())
