# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/wizard3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wiz_3(object):
    def setupUi(self, Wiz_3):
        Wiz_3.setObjectName("Wiz_3")
        Wiz_3.resize(493, 330)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Wiz_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Wiz_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.videoList = QtWidgets.QListWidget(Wiz_3)
        self.videoList.setObjectName("videoList")
        self.horizontalLayout.addWidget(self.videoList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addB = QtWidgets.QPushButton(Wiz_3)
        self.addB.setObjectName("addB")
        self.verticalLayout.addWidget(self.addB)
        self.removeB = QtWidgets.QPushButton(Wiz_3)
        self.removeB.setObjectName("removeB")
        self.verticalLayout.addWidget(self.removeB)
        self.processB = QtWidgets.QPushButton(Wiz_3)
        self.processB.setObjectName("processB")
        self.verticalLayout.addWidget(self.processB)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.previousB = QtWidgets.QPushButton(Wiz_3)
        self.previousB.setObjectName("previousB")
        self.verticalLayout.addWidget(self.previousB)
        self.nextB = QtWidgets.QPushButton(Wiz_3)
        self.nextB.setObjectName("nextB")
        self.verticalLayout.addWidget(self.nextB)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Wiz_3)
        QtCore.QMetaObject.connectSlotsByName(Wiz_3)

    def retranslateUi(self, Wiz_3):
        _translate = QtCore.QCoreApplication.translate
        Wiz_3.setWindowTitle(_translate("Wiz_3", "Create *.DADS File Wizard (2/x)"))
        self.label.setText(_translate("Wiz_3", "Select videos(s)"))
        self.addB.setText(_translate("Wiz_3", "Add"))
        self.removeB.setText(_translate("Wiz_3", "Remove"))
        self.processB.setText(_translate("Wiz_3", "Video\n"
"Process"))
        self.previousB.setText(_translate("Wiz_3", "Previous"))
        self.nextB.setText(_translate("Wiz_3", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wiz_3 = QtWidgets.QWidget()
    ui = Ui_Wiz_3()
    ui.setupUi(Wiz_3)
    Wiz_3.show()
    sys.exit(app.exec_())
