# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pages/UIs/wizard3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wiz_3(object):
    def setupUi(self, Wiz_3):
        Wiz_3.setObjectName("Wiz_3")
        Wiz_3.resize(493, 330)
        self.label = QtWidgets.QLabel(Wiz_3)
        self.label.setGeometry(QtCore.QRect(180, 10, 141, 21))
        self.label.setObjectName("label")
        self.nextB = QtWidgets.QPushButton(Wiz_3)
        self.nextB.setGeometry(QtCore.QRect(390, 290, 89, 24))
        self.nextB.setObjectName("nextB")
        self.previousB = QtWidgets.QPushButton(Wiz_3)
        self.previousB.setGeometry(QtCore.QRect(390, 260, 89, 25))
        self.previousB.setObjectName("previousB")
        self.addB = QtWidgets.QPushButton(Wiz_3)
        self.addB.setGeometry(QtCore.QRect(390, 40, 89, 25))
        self.addB.setObjectName("addB")
        self.removeB = QtWidgets.QPushButton(Wiz_3)
        self.removeB.setGeometry(QtCore.QRect(390, 70, 89, 25))
        self.removeB.setObjectName("removeB")
        self.processB = QtWidgets.QPushButton(Wiz_3)
        self.processB.setGeometry(QtCore.QRect(390, 100, 89, 51))
        self.processB.setObjectName("processB")
        self.videoList = QtWidgets.QListWidget(Wiz_3)
        self.videoList.setGeometry(QtCore.QRect(10, 40, 371, 271))
        self.videoList.setObjectName("videoList")

        self.retranslateUi(Wiz_3)
        QtCore.QMetaObject.connectSlotsByName(Wiz_3)

    def retranslateUi(self, Wiz_3):
        _translate = QtCore.QCoreApplication.translate
        Wiz_3.setWindowTitle(_translate("Wiz_3", "Create *.DADS File Wizard (2/x)"))
        self.label.setText(_translate("Wiz_3", "Select videos(s)"))
        self.nextB.setText(_translate("Wiz_3", "Next"))
        self.previousB.setText(_translate("Wiz_3", "Previous"))
        self.addB.setText(_translate("Wiz_3", "Add"))
        self.removeB.setText(_translate("Wiz_3", "Remove"))
        self.processB.setText(_translate("Wiz_3", "Video\n"
"Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wiz_3 = QtWidgets.QWidget()
    ui = Ui_Wiz_3()
    ui.setupUi(Wiz_3)
    Wiz_3.show()
    sys.exit(app.exec_())
