# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pages/wizard1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wiz_1(object):
    def setupUi(self, Wiz_1):
        Wiz_1.setObjectName("Wiz_1")
        Wiz_1.resize(488, 330)
        self.label = QtWidgets.QLabel(Wiz_1)
        self.label.setGeometry(QtCore.QRect(180, 10, 141, 21))
        self.label.setObjectName("label")
        self.nextB = QtWidgets.QPushButton(Wiz_1)
        self.nextB.setGeometry(QtCore.QRect(390, 290, 89, 25))
        self.nextB.setObjectName("nextB")
        self.baglist = QtWidgets.QListWidget(Wiz_1)
        self.baglist.setGeometry(QtCore.QRect(10, 40, 371, 281))
        self.baglist.setDragEnabled(False)
        self.baglist.setObjectName("baglist")
        self.widget = QtWidgets.QWidget(Wiz_1)
        self.widget.setGeometry(QtCore.QRect(390, 40, 91, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addB = QtWidgets.QPushButton(self.widget)
        self.addB.setObjectName("addB")
        self.verticalLayout.addWidget(self.addB)
        self.removeB = QtWidgets.QPushButton(self.widget)
        self.removeB.setObjectName("removeB")
        self.verticalLayout.addWidget(self.removeB)
        self.moveUpB = QtWidgets.QPushButton(self.widget)
        self.moveUpB.setObjectName("moveUpB")
        self.verticalLayout.addWidget(self.moveUpB)
        self.moveDownB = QtWidgets.QPushButton(self.widget)
        self.moveDownB.setObjectName("moveDownB")
        self.verticalLayout.addWidget(self.moveDownB)
        self.sortB = QtWidgets.QPushButton(self.widget)
        self.sortB.setObjectName("sortB")
        self.verticalLayout.addWidget(self.sortB)

        self.retranslateUi(Wiz_1)
        QtCore.QMetaObject.connectSlotsByName(Wiz_1)

    def retranslateUi(self, Wiz_1):
        _translate = QtCore.QCoreApplication.translate
        Wiz_1.setWindowTitle(_translate("Wiz_1", "Create *.DADS File Wizard "))
        self.label.setText(_translate("Wiz_1", "Select rosbag file(s)"))
        self.nextB.setText(_translate("Wiz_1", "Next"))
        self.baglist.setSortingEnabled(False)
        self.addB.setText(_translate("Wiz_1", "Add"))
        self.removeB.setText(_translate("Wiz_1", "Remove"))
        self.moveUpB.setText(_translate("Wiz_1", "Move Up"))
        self.moveDownB.setText(_translate("Wiz_1", "Move Down"))
        self.sortB.setText(_translate("Wiz_1", "Sort A->Z"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wiz_1 = QtWidgets.QWidget()
    ui = Ui_Wiz_1()
    ui.setupUi(Wiz_1)
    Wiz_1.show()
    sys.exit(app.exec_())
